### ISSUE TITLE
Adding New elements to the website and improving the Code Quality

### ISSUE THREAD

**Issue by ayushmangarg2003** [DevTrolex/Hacktoberfest-2022#3]
He this website has nothing but footer , so if you could tell me what kind of websites this is then I can add necessary element in the website and also the code is unorganized so I would organize it so that it is manageable in future.

**Comment by DevTrolex** [comment]
Hi no need to change in code simply fork the repo go to index.html add some dummy code in comment ill merge your PR-<>-

**Comment by ayushmangarg2003** [comment]
ok I will make some change in a comment pull a request
